apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-website
  template:
    metadata: 
      name: my-website
      labels:
        app: my-website
    spec:
      containers:
        - name: web-image
          image: fatmaabdelhameed/server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80