apiVersion: v1
kind: Service
metadata:
  name: node-port-service
     
spec:
  type: NodePort
  selector:
    app: my-website
  ports:
    - port: 8080 # service
      targetPort: 5080  # pod
      nodePort: 30005  # any port between 30000 and 32767
